import type { Metadata } from "next";
import { Alex_Brush, Montserrat } from "next/font/google";
import "./globals.css";

const alexBrush = Alex_Brush({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-alexBrush",
});

const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${alexBrush.variable} overflow-x-hidden relative`}
      >
        <h1 className="pretitle">layout</h1>
        <button className="btn btn-lg btn-accent">Click me</button>
        {children}
      </body>
    </html>
  );
}
